### ISSUE TITLE
About ME

### ISSUE THREAD

**Issue by echo-864** [echo-864/About_ME#1]
This repo is just for introduction... If I've any updates, I'll post here! :heart: :heart_eyes:

**Comment by smartclash** [comment]
Keep going, and from now, learn not to use spaces while naming a file. `About Me.md` is bad. You should instead do this `AboutMe.md`. Good luck :)

**Comment by echo-864** [comment]
Ok dude 👍😍

**Comment by echo-864** [comment]
> Keep going, and from now, learn not to use spaces while naming a file. `About Me.md` is bad. You should instead do this `AboutMe.md`. Good luck :)

Issue solved! :+1:
